# Generated by Django 4.2.7 on 2025-10-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_add_booking_refund_policy_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.CharField(default='global', max_length=50, unique=True)),
                ('navigation_items', models.JSONField(blank=True, default=list, help_text='Main navigation menu items')),
                ('footer_description', models.TextField(blank=True, help_text='Company description in footer')),
                ('footer_links', models.JSONField(blank=True, default=list, help_text='Footer navigation links')),
                ('social_links', models.JSONField(blank=True, default=list, help_text='Social media links')),
                ('copyright_text', models.CharField(blank=True, help_text='Copyright text', max_length=200)),
                ('site_title', models.CharField(blank=True, help_text='Default site title', max_length=200)),
                ('site_description', models.TextField(blank=True, help_text='Default site description', max_length=500)),
                ('site_keywords', models.TextField(blank=True, help_text='Default SEO keywords')),
                ('og_image', models.URLField(blank=True, help_text='Default Open Graph image URL')),
                ('twitter_handle', models.CharField(blank=True, help_text='Twitter handle (without @)', max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_address', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
