# Generated by Django 4.2.7 on 2025-10-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20251024_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show_pricing',
            field=models.BooleanField(default=False, help_text='Show pricing instead of CTA buttons'),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_primary_text',
            field=models.CharField(blank=True, default='Get Quick Quote', help_text='Primary CTA button text', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_primary_link',
            field=models.CharField(blank=True, default='/contact', help_text='Primary CTA button link', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_secondary_text',
            field=models.CharField(blank=True, default='Schedule Consultation', help_text='Secondary CTA button text', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_secondary_link',
            field=models.CharField(blank=True, default='/book-consultation', help_text='Secondary CTA button link', max_length=200),
        ),
    ]
