# Generated by Django 4.2.7 on 2025-10-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_add_revenue_tracking'),
    ]

    operations = [
        # Add new fields to ConsultationSlot
        migrations.AddField(
            model_name='consultationslot',
            name='communication_method',
            field=models.CharField(
                choices=[
                    ('zoom', 'Zoom'),
                    ('teams', 'Microsoft Teams'),
                    ('direct_call', 'Direct Call'),
                    ('google_meet', 'Google Meet')
                ],
                default='zoom',
                help_text='Preferred communication method for this slot',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='consultationslot',
            name='requires_payment',
            field=models.BooleanField(
                default=True,
                help_text='Whether this slot requires upfront payment'
            ),
        ),
        migrations.AddField(
            model_name='consultationslot',
            name='payment_amount',
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text='Booking fee amount (refundable/adjustable)',
                max_digits=10
            ),
        ),
        # Add communication_method to Booking
        migrations.AddField(
            model_name='booking',
            name='communication_method',
            field=models.CharField(
                choices=[
                    ('zoom', 'Zoom'),
                    ('teams', 'Microsoft Teams'),
                    ('direct_call', 'Direct Call'),
                    ('google_meet', 'Google Meet')
                ],
                default='zoom',
                help_text='Selected communication method for this booking',
                max_length=20
            ),
        ),
    ]
