# Generated by create_lead_migration.py
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_add_tracking_fields'),
    ]

    operations = [
        # Add new required fields with defaults
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='project_type',
            field=models.CharField(default='General Consultation', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='timeline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_followup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Update existing name field based on first_name and last_name if needed
        migrations.RunSQL(
            "UPDATE leads_lead SET first_name = COALESCE(split_part(name, ' ', 1), name, '') WHERE name IS NOT NULL AND name != '';",
            reverse_sql="UPDATE leads_lead SET name = first_name || ' ' || last_name WHERE first_name IS NOT NULL OR last_name IS NOT NULL;"
        ),
        migrations.RunSQL(
            "UPDATE leads_lead SET last_name = COALESCE(split_part(name, ' ', 2), '') WHERE name IS NOT NULL AND name != '' AND position(' ' in name) > 0;",
            reverse_sql="UPDATE leads_lead SET name = first_name || ' ' || last_name WHERE first_name IS NOT NULL OR last_name IS NOT NULL;"
        ),
        # Convert message to description if description is empty
        migrations.RunSQL(
            "UPDATE leads_lead SET description = COALESCE(message, 'No description provided') WHERE description = 'No description provided' AND message IS NOT NULL AND message != '';",
            reverse_sql="UPDATE leads_lead SET message = description WHERE message IS NULL OR message = '';"
        ),
    ]