# Generated by Django 4.2.7 on 2025-10-10 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0003_add_communication_and_payment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('currency', models.CharField(default='usd', help_text='Payment currency code', max_length=3)),
                ('stripe_payment_intent_id', models.CharField(help_text='Stripe Payment Intent ID', max_length=255, unique=True)),
                ('stripe_payment_status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('processing', 'Processing'),
                        ('succeeded', 'Succeeded'),
                        ('failed', 'Failed'),
                        ('refunded', 'Refunded'),
                        ('partially_refunded', 'Partially Refunded')
                    ],
                    default='pending',
                    max_length=30
                )),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was completed', null=True)),
                ('refunded', models.BooleanField(default=False, help_text='Whether this payment has been refunded')),
                ('refunded_at', models.DateTimeField(blank=True, help_text='Timestamp when refund was processed', null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount refunded', max_digits=10)),
                ('refund_reason', models.TextField(blank=True, help_text='Reason for refund')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='consultations.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
